# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Cloudskills Python App

on:
  push:
    branches: 
     - '*'
  pull_request:
    branches:
     - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f Week-5-CICD/ci-pythonapp/Application/requirements.txt ]; then pip install -r Week-5-CICD/ci-pythonapp/Application/requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 Week-5-CICD/ci-pythonapp/. --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 Week-5-CICD/ci-pythonapp/. --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        mkdir Week-5-CICD/ci-pythonapp/testResults
        pytest Week-5-CICD/ci-pythonapp/Tests/unit_tests --junitxml=./Week-5-CICD/ci-pythonapp/testResults/results.xml
        
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.12
      with:
        files: ./testResults/results.xml
